import React,{useState} from 'react';
import {ProjectArtwork} from './Artworks';
import './DemoSites.css';

function Orbit(){
 const [tasks,setTasks]=useState([{id:1,title:'Design the new homepage',done:false},{id:2,title:'Review brand direction',done:true},{id:3,title:'Share prototype with the team',done:false}]);
 const [draft,setDraft]=useState(''); const [filter,setFilter]=useState('All');
 return <><div className="demo-intro"><small>YOUR PERSONAL WORKSPACE</small><h1>A little focus.<br/>A lot of progress.</h1><p>Clear your head. Make room for the work that matters.</p></div><div className="orbit-work"><div className="demo-stats"><div><b>{tasks.length}</b><span>Total tasks</span></div><div><b>{tasks.filter(t=>!t.done).length}</b><span>In progress</span></div><div><b>{tasks.filter(t=>t.done).length}</b><span>Completed</span></div></div><div className="task-heading"><h2>My tasks</h2><div>{['All','Active','Done'].map(f=><button className={filter===f?'chosen':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></div><form onSubmit={e=>{e.preventDefault();if(draft.trim()){setTasks([...tasks,{id:Date.now(),title:draft.trim(),done:false}]);setDraft('');}}}><input aria-label="New task" placeholder="What needs doing?" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={120} required/><button>Add task +</button></form><div className="task-list">{tasks.filter(t=>filter==='All'||(filter==='Done'?t.done:!t.done)).map(t=><label key={t.id}><input type="checkbox" checked={t.done} onChange={()=>setTasks(tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}/><span style={{textDecoration:t.done?'line-through':'none'}}>{t.title}</span><button aria-label={`Delete ${t.title}`} onClick={e=>{e.preventDefault();setTasks(tasks.filter(x=>x.id!==t.id));}}>×</button></label>)}</div><p className="demo-note">Try adding and completing a task. This demo resets when you leave.</p></div></>;
}
function Aura(){const [color,setColor]=useState('Sand'),[qty,setQty]=useState(0);return <><div className="aura-product"><div className="demo-product-art" data-finish={color}><ProjectArtwork type="aura"/></div><div className="demo-product-copy"><small>LESS NOISE. MORE YOU.</small><h1>Meet your<br/>quiet place.</h1><p>Over-ear comfort. Rich, detailed sound. A little space from everything else.</p><h2>Aura One <span>₹12,900</span></h2><div className="finish-picker"><span>Finish: {color}</span><div>{['Sand','Stone','Midnight'].map((c,i)=><button key={c} aria-label={`${c} finish`} aria-pressed={color===c} onClick={()=>setColor(c)} style={{background:['#d0bea5','#9a9b96','#282a30'][i],outline:color===c?'2px solid #282a30':'none'}}/>)}</div></div><button className="demo-primary" onClick={()=>setQty(q=>q+1)}>Add to demo bag ↗</button><p role="status">{qty?`${qty} item${qty>1?'s':''} in your demo bag · ₹${(qty*12900).toLocaleString('en-IN')}`:'Choose your finish. Find your rhythm.'}</p>{qty>0&&<button className="demo-text-button" onClick={()=>setQty(0)}>Empty bag</button>}</div></div><div className="demo-features">{[['40h','Keep the music going'],['Soft fit','Made for slow Sundays'],['Your space','Active noise cancellation']].map(([n,t])=><div key={n}><h2>{n}</h2><p>{t}</p></div>)}</div><p className="demo-note">Fictional product demo. No orders or payments are processed.</p></>}
const spaces=[{name:'The Courtyard House',type:'Residential',year:'2026',n:'01'},{name:'Still Studio',type:'Commercial',year:'2025',n:'02'},{name:'A House in the Hills',type:'Residential',year:'2025',n:'03'}];
function Forma(){const [filter,setFilter]=useState('All'),[selected,setSelected]=useState(null);return <><div className="demo-intro"><small>ARCHITECTURE / INTERIORS / EVERYDAY LIFE</small><h1>Room to<br/>live a little.</h1><p>Thoughtful spaces, natural materials, and a quieter way of living.</p></div><div className="forma-banner"><ProjectArtwork type="forma"/></div><div className="task-heading"><h2>Selected spaces</h2><div>{['All','Residential','Commercial'].map(f=><button key={f} className={filter===f?'chosen':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="space-list">{spaces.filter(s=>filter==='All'||s.type===filter).map(s=><button key={s.name} onClick={()=>setSelected(selected===s.name?null:s.name)} aria-expanded={selected===s.name}><span>{s.n}</span><div><h2>{s.name}</h2><p>{s.type} · {s.year}</p>{selected===s.name&&<p className="space-detail">An independent concept exploring warm timber, filtered daylight, and generous open spaces. Designed around the small rituals of everyday life.</p>}</div><b>{selected===s.name?'−':'↗'}</b></button>)}</div><a className="demo-primary" href="mailto:webdesignss.site@gmail.com?subject=Architecture%20website%20enquiry">Let's design your next chapter ↗</a></>}
const lineup=[['Friday','18:00','Soft Signal','Ambient / live'],['Friday','20:00','After Hours','Electronic'],['Saturday','17:00','Wild Form','Alternative'],['Saturday','21:00','Neon Season','Dance / live']];
function Offgrid(){const [day,setDay]=useState('Friday'),[pass,setPass]=useState('Weekend'),[reserved,setReserved]=useState(false);return <><div className="festival-intro"><small>INDEPENDENT MUSIC. SHARED MOMENTS.</small><h1>GET LOST.<br/>FIND YOUR<br/><em>PEOPLE.</em></h1><p>A fictional weekend of sound, art, and staying a little longer.</p><button className="demo-primary" onClick={()=>document.getElementById('demo-lineup').scrollIntoView({behavior:'smooth'})}>Explore the lineup ↓</button></div><section id="demo-lineup"><div className="task-heading"><h2>The lineup</h2><div>{['Friday','Saturday'].map(d=><button className={day===d?'chosen':''} onClick={()=>setDay(d)} key={d}>{d}</button>)}</div></div>{lineup.filter(a=>a[0]===day).map(a=><div className="lineup-row" key={a[2]}><time>{a[1]}</time><h2>{a[2]}</h2><span>{a[3]}</span></div>)}</section><div className="pass-box"><div><small>MAKE A WEEKEND OF IT</small><h2>Your place in the crowd.</h2><p>Explore the ticket selection experience.</p></div><div><label>Choose a pass<select value={pass} onChange={e=>{setPass(e.target.value);setReserved(false);}}><option>Weekend</option><option>Friday</option><option>Saturday</option></select></label><button className="demo-primary" onClick={()=>setReserved(true)}>Preview reservation ↗</button><p role="status">{reserved?`${pass} pass selected. Demo only—no reservation made.`:'No payment or personal information required.'}</p></div></div></>}
export default function DemoSites({project}){return <div className={`demo-site demo-${project.id}`}><div className="demo-topline"><a href="#work">← Back to WebDesignss</a><span>INTERACTIVE CONCEPT WEBSITE</span></div><nav className="demo-nav"><a href={`#/project/${project.id}`} className="demo-logo">{project.name}</a><a href="mailto:webdesignss.site@gmail.com">Get in touch ↗</a></nav>{project.id==='orbit'?<Orbit/>:project.id==='aura'?<Aura/>:project.id==='forma'?<Forma/>:<Offgrid/>}<footer className="demo-footer"><b>{project.name}</b><span>Designed & built by WebDesignss</span><a href="#work">Explore more work ↗</a></footer></div>}
