import React, { Suspense, lazy, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowLeft, ArrowRight, Plus, Minus, X, Menu, Globe2, Copy, Check, Volume2, VolumeX, Sun, Moon } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { projects } from './projects';
import { ProjectArtwork, BrandBoard, Star } from './Artworks';
import './style.css';

gsap.registerPlugin(ScrollTrigger);

import RgbCursor from './RgbCursor';
import HeroMotion from './HeroMotion';
import DemoSites from './DemoSites';
import VideoBackground from './VideoBackground';
import ParticleFooter from './ParticleFooter';
import CurvedScroll from './CurvedScroll';

const asset = (path) => `${import.meta.env.BASE_URL}${path}`;
const Tunnel=lazy(()=>import('./Scene').then(m=>({default:m.Tunnel})));
const EMAIL='webdesignss.site@gmail.com';
const PHONE='9948429459';
const services=[
  {name:'Web design & development', tags:'STRATEGY · DESIGN · BUILD', text:'Distinctive, responsive websites built around your business. From the first wireframe to the final interaction, every detail has a purpose.', items:['Business & portfolio websites','Responsive development','Motion & interaction design','Performance & accessibility']},
  {name:'Brand identity & art direction', tags:'IDENTITY · VISUAL LANGUAGE', text:'A clear point of view, made visible. We create expressive identities that connect your story across your website and every brand touchpoint.', items:['Visual identity','Typography & colour systems','Creative direction','Brand guidelines']},
  {name:'Digital product design', tags:'UI / UX · DESIGN SYSTEMS', text:'Thoughtful interfaces for real people. We turn complex ideas into intuitive digital products that feel natural from the first click.', items:['User flows & wireframes','Interface design','Interactive prototypes','Scalable design systems']},
];

function useClock(){const [time,setTime]=useState('');useEffect(()=>{const update=()=>setTime(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()));update();const id=setInterval(update,30000);return()=>clearInterval(id);},[]);return time;}
function Grid(){return <div className="page-grid" aria-hidden="true"><i/><i/><i/><i/><span className="cross c1">+</span><span className="cross c2">+</span><span className="cross c3">+</span><span className="cross c4">+</span></div>;}
function SoundButton(){
  const [on,setOn]=useState(false);const audio=useRef(null);
  useEffect(()=>()=>{audio.current?.close();},[]);
  const toggle=async()=>{try{if(!audio.current){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const ac=new AudioContext();const gain=ac.createGain();gain.gain.value=.018;gain.connect(ac.destination);[130.81,196,261.63].forEach((freq,i)=>{const osc=ac.createOscillator();osc.type='sine';osc.frequency.value=freq;const g=ac.createGain();g.gain.value=i===0?.45:.22;osc.connect(g);g.connect(gain);osc.start();});audio.current=ac;}if(on){await audio.current.suspend();setOn(false);}else{await audio.current.resume();setOn(true);}}catch{setOn(false);}};
  return <button onClick={toggle} className="utility-button sound-button" aria-label={on?'Mute ambient sound':'Play ambient sound'} aria-pressed={on}><span>SOUND</span><span className={`equalizer ${on?'playing':''}`}><i/><i/><i/><i/></span></button>;
}
function Header({theme,setTheme,detail}){const [menu,setMenu]=useState(false);useEffect(()=>{setMenu(false);},[detail]);return <>
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="site-header"><a href="#home" className="wordmark" aria-label="WebDesignss home"><img className="brand-logo" src={asset('webdesignss-logo.png')} alt=""/><span className="brand-name">WEB DESIGNSS</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#work">WORK <span>04</span></a><a href="#about">ABOUT</a><a href="#contact">LET’S TALK <ArrowUpRight size={13}/></a></nav><div className="header-utilities"><button className="utility-button theme-button" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`}>THEME <span>[{theme==='dark'?'D':'L'}]</span></button><SoundButton/><button className="mobile-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
  {menu&&<nav className="mobile-menu" aria-label="Mobile navigation">{[['work','Selected work'],['about','About the studio'],['contact','Let’s talk']].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<ArrowUpRight/></a>)}</nav>}
</>;}
function Coordinates(){const el=useRef(null);useEffect(()=>{let last=0;const move=e=>{if(performance.now()-last<60)return;last=performance.now();if(el.current)el.current.textContent=`${String(e.clientX).padStart(4,'0')} X  ${String(e.clientY).padStart(4,'0')} Y`;};window.addEventListener('pointermove',move,{passive:true});return()=>window.removeEventListener('pointermove',move);},[]);return <span ref={el} className="coordinates">0000 X&nbsp; 0000 Y</span>;}
function Stickers(){return <div className="stickers" aria-hidden="true"><span className="sticker sticker-flower">✳</span><span className="sticker sticker-label">MAKE<br/>IT MATTER.</span><span className="sticker sticker-eye"><i/><i/></span><span className="sticker sticker-heart">♥</span><span className="sticker sticker-spark">✦</span><span className="sticker sticker-disc">GOOD<br/>BY DESIGN<small>✳</small></span><span className="sticker sticker-code">&lt;/&gt;</span><span className="sticker sticker-plus">✳</span></div>;}
function Hero(){const time=useClock();return <section className="hero" id="home" aria-labelledby="hero-title"><div className="hero-atmosphere"/><HeroMotion/><Grid/><div className="hero-top"><p>We’re WebDesignss, an independent digital studio turning ambitious ideas into thoughtful brands and websites.</p></div><div className="hero-heading"><span className="eyebrow"><i className="status-dot"/> AVAILABLE FOR SELECT PROJECTS</span><h1 id="hero-title">WE BRING<br/>CRAFT & FEELING<br/>TO DIGITAL WORK<span className="title-period">.</span></h1></div><div className="hero-bottom mono"><span>GMT+5:30 IN <b>{time}</b></span><Coordinates/><a href="#about" className="explore-link">SCROLL TO EXPLORE <ArrowDown size={14}/></a><Globe2 className="hero-globe" size={31} strokeWidth={1}/></div></section>;}
function About(){return <section className="about section-pad" id="about"><div className="section-label"><span>01 / THE STUDIO</span><span>SMALL STUDIO. BIG POSSIBILITIES.</span></div><div className="about-content"><div className="about-emblem"><div className="music-cd-stage" role="img" aria-label="Spinning holographic 3D music CD"><div className="music-cd"><div className="music-cd-face"><span className="cd-title">WEBDESIGNSS</span><span className="cd-note">♫</span><span className="cd-caption">STUDIO SESSIONS · VOL. 01<br/>DIGITAL AUDIO / STEREO</span></div><span className="cd-hub"/></div></div><span className="signature">a little different.</span><p>Based in India.<br/>Creating for everywhere.</p></div><div className="about-copy"><h2>Good design makes you look.<br/><span>Great design makes<br/>you feel.</span></h2><p>We bring clarity, character, and a little unexpected to the digital world. Thoughtful websites. Distinctive identities. Experiences that stay with you.</p><p className="muted">From the first “what if” to the final pixel, we partner with people who care about what they put into the world.</p><a href="#contact" className="text-link">Have something in mind? Let’s talk <ArrowUpRight size={19}/></a></div></div><div className="studio-strip mono"><span><i className="status-dot"/> OPEN FOR COLLABORATIONS</span><span>DESIGN-LED. DETAIL-OBSESSED.</span><span>INDEPENDENT & INTENTIONAL ↗</span></div></section>;}
function Work(){return <section className="work section-pad" id="work"><div className="section-label"><span>02 / SELECTED EXPLORATIONS</span><span>2026 — ONGOING</span></div><div className="work-heading"><h2>Work that<br/><span>speaks for itself.</span></h2><div><p>A few possibilities.<br/>Each with a point of view.</p><span className="mono concept-note">INDEPENDENT CONCEPT PROJECTS</span></div></div><div className="project-grid">{projects.map((p,i)=><a href={`#/project/${p.id}`} className={`project-card card-${p.id} reveal`} key={p.id} aria-label={`View ${p.name} interactive demo`}><div className="project-image"><ProjectArtwork type={p.cover}/><span className="project-badge">CONCEPT / {p.number}</span><span className="project-open"><ArrowUpRight/></span></div><div className="project-caption"><div><h3>{p.name}</h3><span>{p.category}</span></div><span>{p.year}<ArrowUpRight size={17}/></span></div></a>)}</div><div className="work-footnote mono"><span>EXPLORING WHAT’S NEXT, ONE IDEA AT A TIME.</span><Star/></div></section>;}
function Services(){const [open,setOpen]=useState(0);return <section className="services section-pad" id="services"><div className="section-label"><span>03 / WHAT WE DO</span><span>FROM FIRST IDEA TO FINAL DETAIL</span></div><div className="services-layout"><h2>Thoughtfully<br/>designed.<br/><span>Beautifully built.</span></h2><div className="service-list">{services.map((s,i)=><div className={`service ${open===i?'is-open':''}`} key={s.name}><button className="service-trigger" aria-expanded={open===i} aria-controls={`service-${i}`} onClick={()=>setOpen(open===i?null:i)}><span className="service-number">0{i+1}</span><span>{s.name}</span>{open===i?<Minus size={19}/>:<Plus size={19}/>}</button><div className="service-content" id={`service-${i}`} hidden={open!==i}><span className="mono">{s.tags}</span><p>{s.text}</p><ul>{s.items.map(item=><li key={item}>{item}</li>)}</ul></div></div>)}</div></div></section>;}
function Warp(){const ref=useRef(null);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const ctx=gsap.context(()=>{gsap.fromTo('.warp-arrow',{scale:.5,rotation:-15,opacity:1},{scale:14,rotation:25,opacity:0,ease:'power2.in',scrollTrigger:{trigger:ref.current,start:'top 85%',end:'center center',scrub:1}});gsap.fromTo('.warp-title',{opacity:.1,scale:.8},{opacity:1,scale:1,scrollTrigger:{trigger:ref.current,start:'top 55%',end:'center center',scrub:1}});},ref);return()=>ctx.revert();},[]);return <section className="warp" ref={ref}><Suspense fallback={null}><Tunnel/></Suspense><svg className="warp-arrow" viewBox="0 0 160 180" aria-hidden="true"><defs><linearGradient id="arrowGradient" x1="0" x2="1" y1="0" y2="1"><stop stopColor="#8dceff"/><stop offset=".5" stopColor="#388dff"/><stop offset="1" stopColor="#354acc"/></linearGradient></defs><path d="M20 12 Q10 6 12 25 L27 149 Q29 164 40 151 L70 116 L109 157 Q117 164 125 157 L138 144 Q146 135 138 127 L98 88 L143 71 Q156 65 141 58Z" fill="url(#arrowGradient)" stroke="#80b6ff" strokeWidth="2"/></svg><div className="warp-title"><span className="mono">A LITTLE CURIOSITY GOES A LONG WAY.</span><h2>MAKE SOMETHING<br/><em>THAT MATTERS.</em></h2><Star/></div><span className="warp-bottom mono">KEEP EXPLORING ↓</span></section>;}
function Contact(){const [copied,setCopied]=useState(false);const time=useClock();const copy=async()=>{try{await navigator.clipboard.writeText(EMAIL);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{window.location.href=`mailto:${EMAIL}`;}};return <footer className="contact section-pad" id="contact"><Grid/><div className="section-label"><span>04 / YOUR NEXT GOOD IDEA</span><span><i className="status-dot"/> LET’S MAKE IT HAPPEN</span></div><div className="contact-sculpture" aria-hidden="true"><span>good</span><span>things</span><span>ahead.</span></div><div className="contact-heading"><h2>LET’S CREATE<br/>SOMETHING<br/><span>EXTRAORDINARY.</span></h2><a href={`mailto:${EMAIL}?subject=Let%E2%80%99s%20create%20something%20extraordinary`} className="contact-orb" aria-label="Start a project by email"><ArrowUpRight/></a></div><div className="contact-details"><div><span className="mono">HAVE AN IDEA? SAY HELLO.</span><div className="email-row"><a href={`mailto:${EMAIL}`}>{EMAIL}</a><button onClick={copy} aria-label={copied?'Email address copied':'Copy email address'}>{copied?<Check size={18}/>:<Copy size={18}/>}</button></div><span className="copy-status" role="status">{copied?'Email copied. Let’s make something good.':''}</span></div><a className="phone-link" href={`tel:${PHONE}`}><span className="mono">PREFER A CONVERSATION?</span><span>{PHONE} <ArrowUpRight size={18}/></span></a></div><div className="footer-line mono"><span>© {new Date().getFullYear()} WEBDESIGNSS</span><span>INDIA · {time} IST</span><a href="#home">BACK TO TOP <ArrowUpRight size={13}/></a></div></footer>;}
function Home(){return <><Hero/><About/><Work/><Services/><Contact/></>;}
function ProjectPage({project}){const next=projects[(projects.indexOf(project)+1)%projects.length];return <><article className={`case-study case-${project.id}`} style={{'--project-accent':project.color}}><div className="case-top section-pad"><a href="#work" className="back-link mono"><ArrowLeft size={15}/> BACK TO SELECTED WORK</a><div className="case-meta mono"><span>INDEPENDENT CONCEPT / {project.number}</span><span>{project.category} — {project.year}</span></div><h1>{project.name}<ArrowUpRight/></h1><div className="case-intro"><h2>{project.headline.split('\n').map((s,i)=><React.Fragment key={s}>{i>0&&<br/>}{s}</React.Fragment>)}</h2><div><p>{project.intro}</p><span className="concept-disclosure">Self-initiated design exploration. Not commissioned client work.</span></div></div><div className="case-specs"><div><span>SECTOR</span><p>{project.type}</p></div><div><span>CAPABILITIES</span><p>{project.services.join(' / ')}</p></div><div><span>YEAR</span><p>{project.year}</p></div></div></div><div className="case-main-art"><ProjectArtwork type={project.cover}/></div><section className="case-story section-pad"><div className="section-label"><span>01 / THE THINKING</span><span>CLARITY BEFORE COMPLEXITY.</span></div><div className="story-columns"><h2>A considered<br/>point of view.</h2><div><h3>The challenge</h3><p>{project.challenge}</p><h3>The approach</h3><p>{project.approach}</p></div></div></section><div className="case-brand section-pad"><BrandBoard project={project}/></div><section className="case-solution section-pad"><div className="section-label"><span>02 / THE EXPERIENCE</span><span>DESIGNED DOWN TO THE DETAILS.</span></div><div className="story-columns"><h2>{project.quote}</h2><div><p>{project.solution}</p><ul className="solution-list">{project.details.map((d,i)=><li key={d}><span>0{i+1}</span>{d}<ArrowUpRight size={18}/></li>)}</ul></div></div><div className="device-composition"><div className="desktop-device"><div className="device-bar"><i/><i/><i/><span>{project.name.toLowerCase().replace('®','')} / concept preview</span></div><ProjectArtwork type={project.cover} variant/></div><div className="mobile-device"><span className="phone-notch"/><ProjectArtwork type={project.cover}/><div className="mobile-device-copy"><span>{project.name}</span><p>{project.quote}</p><ArrowUpRight/></div></div></div></section><div className="case-cta section-pad"><span className="mono">IMAGINE WHAT WE COULD MAKE TOGETHER.</span><h2>Your idea.<br/>Our next obsession.</h2><a className="pill-button" href={`mailto:${EMAIL}?subject=${encodeURIComponent(`A project inspired by ${project.name}`)}`}>Let’s talk about your project <ArrowUpRight size={17}/></a></div><a href={`#/project/${next.id}`} className="next-project section-pad"><div><span className="mono">NEXT EXPLORATION / {next.number}</span><h2>{next.name}<ArrowUpRight/></h2></div><div className="next-preview"><ProjectArtwork type={next.cover}/></div></a></article><Contact/></>;}
function App(){
  const [route,setRoute]=useState(window.location.hash);
  const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('webdesignss-theme')||'dark';}catch{return 'dark';}});
  const project=route.startsWith('#/project/')?projects.find(p=>p.id===route.split('/')[2]):null;
  const invalid=route.startsWith('#/project/')&&!project;
  const progress=useRef(null);
  useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('webdesignss-theme',theme);}catch{}},[theme]);
  useEffect(()=>{const update=()=>setRoute(window.location.hash);window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
  useEffect(()=>{document.title=project?`${project.name} — Interactive Demo | WebDesignss`:'WebDesignss® — Independent Design & Development';const target=project||invalid?null:(route||'#home').slice(1);const id=setTimeout(()=>{if(project||invalid){window.scrollTo({top:0,behavior:'instant'});}else{document.getElementById(target)?.scrollIntoView({behavior:'instant'});}ScrollTrigger.refresh();},70);return()=>clearTimeout(id);},[route,project,invalid]);
  useEffect(()=>{const ctx=gsap.context(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;gsap.utils.toArray('.reveal').forEach(el=>gsap.fromTo(el,{y:65,opacity:.3},{y:0,opacity:1,duration:.9,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 96%',once:true}}));});return()=>ctx.revert();},[project,invalid]);
  useEffect(()=>{const update=()=>{const h=document.documentElement.scrollHeight-innerHeight;if(progress.current)progress.current.style.transform=`scaleX(${h>0?scrollY/h:0})`;document.body.classList.toggle('is-scrolled',scrollY>60);};window.addEventListener('scroll',update,{passive:true});update();return()=>window.removeEventListener('scroll',update);},[]);
  return <><VideoBackground/><RgbCursor/><div className="reading-progress" ref={progress}/><Header theme={theme} setTheme={setTheme} detail={project?.id}/><main id="main">{invalid?<section className="not-found section-pad"><span className="mono">404 / A LITTLE OFF THE GRID</span><h1>This idea hasn’t<br/>landed yet.</h1><a className="pill-button" href="#work">Explore our work <ArrowRight/></a></section>:project?<DemoSites key={project.id} project={project}/>:<Home/>}</main><ParticleFooter/></>;
}

createRoot(document.getElementById('root')).render(<App/>);
