export const projects = [
  {
    id: 'orbit', number: '01', name: 'Orbit®', category: 'DIGITAL PRODUCT', year: '2026', type: 'SaaS platform', color: '#c4fa63', cover: 'orbit',
    headline: 'Less noise.\nMore momentum.',
    intro: 'A calmer home for ambitious teams. Orbit brings projects, people, and progress together in one beautifully focused workspace.',
    services: ['Product strategy', 'Visual identity', 'UI / UX design', 'Design system'],
    challenge: 'Work tools have a habit of becoming more work. This self-initiated concept explores how a team workspace can make complex information feel approachable without sacrificing depth.',
    approach: 'We started with the daily rhythm of a small creative team. A clear information hierarchy, generous spacing, and an electric green accent give every action a place and every screen room to breathe.',
    solution: 'A modular dashboard connects priorities, activity, and project health. Consistent components make the interface feel familiar from the very first interaction.',
    quote: 'A little less friction. A lot more flow.',
    details: ['A focused daily overview', 'A flexible project workspace', 'An accessible component system'],
    palette: ['#c4fa63', '#17251e', '#f0f2ec', '#728477'],
  },
  {
    id: 'aura', number: '02', name: 'AURA', category: 'E-COMMERCE EXPERIENCE', year: '2026', type: 'Audio & lifestyle', color: '#ebe5d9', cover: 'aura',
    headline: 'Your world.\nBeautifully quiet.',
    intro: 'An immersive digital storefront for a considered audio brand. Designed to make the experience of sound feel almost tangible.',
    services: ['Art direction', 'Brand identity', 'Web design', 'E-commerce UX'],
    challenge: 'Audio is invisible. This independent concept asks how an online store can communicate the tactile quality, quiet confidence, and emotional value of a premium listening experience.',
    approach: 'Warm neutrals, sculptural product compositions, and spacious editorial typography put the product first. Every detail is designed around a slower, more considered buying journey.',
    solution: 'The experience moves from discovery to product detail through a consistent visual story. Clear feature explanations, an intuitive product hierarchy, and restrained motion create confidence without clutter.',
    quote: 'Turn down the world. Turn up the feeling.',
    details: ['An editorial product story', 'A considered shopping journey', 'A warm, tactile visual language'],
    palette: ['#e9e3d7', '#c1aa8e', '#2c2b27', '#faf8f2'],
  },
  {
    id: 'forma', number: '03', name: 'Forma Studio', category: 'BRAND & WEB DESIGN', year: '2026', type: 'Architecture & spaces', color: '#c9bca6', cover: 'forma',
    headline: 'Spaces for\nthe way we live.',
    intro: 'A quiet digital presence for a fictional architecture practice. Natural light, material honesty, and a sense of place, translated into pixels.',
    services: ['Brand strategy', 'Art direction', 'Website design', 'Development direction'],
    challenge: 'An architecture portfolio should communicate the feeling of a space as well as its form. This concept explores an alternative to crowded galleries and technical presentation.',
    approach: 'A warm, earthy palette and measured typography establish an understated identity. Architectural compositions become the main storytelling device, with writing that offers context without competing for attention.',
    solution: 'An image-led project index opens into immersive case studies. Project information remains easy to find while the composition gives each space its own moment.',
    quote: 'Good spaces leave room for living.',
    details: ['An image-led project archive', 'A refined studio identity', 'An immersive project narrative'],
    palette: ['#cabba2', '#383e32', '#f1ecdf', '#8d7358'],
  },
  {
    id: 'offgrid', number: '04', name: 'OFFGRID®', category: 'ART DIRECTION & DIGITAL', year: '2026', type: 'Culture & creative festival', color: '#ff654b', cover: 'offgrid',
    headline: 'Make a little\ncreative noise.',
    intro: 'An expressive identity and digital experience for a fictional gathering of independent minds. A celebration of ideas that refuse to sit still.',
    services: ['Creative direction', 'Visual identity', 'Motion concept', 'Website design'],
    challenge: 'Creative events often look interchangeable. This self-initiated project explores a distinct identity that can hold many voices together while remaining instantly recognizable.',
    approach: 'Oversized typography, punchy coral, and unexpected layouts create an energetic visual system. A playful asterisk becomes the flexible anchor across posters, digital moments, and the event website.',
    solution: 'The design balances expressive campaign graphics with a clear event structure: discover the idea, explore the programme, meet the speakers, and find the practical information.',
    quote: 'Different minds. One electric space.',
    details: ['A flexible campaign identity', 'An expressive event website', 'A playful motion vocabulary'],
    palette: ['#ff654b', '#232329', '#f1eadd', '#d6fc4a'],
  },
];
